### ISSUE TITLE
read_hamiltonian() does not work with lanthanides?

### ISSUE THREAD

**Issue by novidad21** [zerothi/sisl#491]
**Describe the bug**

**Reproducable code**
```
import sisl
fdf=sisl.get_sile("PATH_TO_FDF")
ham=fdf.read_hamiltonian()
```

Freshly installed siesta from master brench yesterday. After running a calculation with SpinOrbit true using psml pseudopotentials downloaded from dojo-pseudo.org the hamiltonian cannot be read:

ValueError: AtomicOrbital does not implement shell h and above!

**Version details**
3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
0.0.0.dev+eacb8351ff416ad9f7f93732777c3d7931c5f711
[lase.zip](https://github.com/zerothi/sisl/files/9672416/lase.zip)

**Comment by zerothi** [comment]
Yes, currently sisl does not implement the h-shell.

**Comment by zerothi** [comment]
Could you please try the latest commit? It should work now :)
Thanks!

**Comment by novidad21** [comment]
Thanks @zerothi it seems the issue resolved. However I still don't really understand the issue here, because in the produced pseudopotential files I see no indication of h shells, it does not go above l=4. But anyway, no it works! Thank you.

**Comment by novidad21** [comment]
Yes, I assumed the same, so I switched to DZ, and still I ran into the same problem.

**Comment by zerothi** [comment]
Hm. Sounds like this really needs to be checked!

**Comment by zerothi** [comment]
I'll just reopen to make me remember

**Comment by zerothi** [comment]
This was related to #462. So fully fixed. Can be closed now.
