### ISSUE TITLE
sisl unit conversion (siesta units to sisl units)

### ISSUE THREAD

**Issue by anshugaur** [zerothi/sisl#570]
Is it possible to convert the units (from Siesta units to sisl units) while converting *.grid.nc file to *.cube file using sgrid or sisl? 
I am using sisl (ver. 0.13.0) and during conversion (using sgrid) or reading the *.grid.nc (in sisl) it shows that the units could not be determined.
I understand that in CDF format files the data is saved in Siesta units (Ry, bohr, etc.) and I would like to convert it to sisl units (eV, angstrom, etc.) for plotting.

Thanks,
Anshu

**Comment by zerothi** [comment]
Hi,

If the filenames of the `*.grid.nc` files are preserved, `sisl` will be able to know the unit automatically. So this sounds like you have changed the filename?

Alternatively you can use the `sgrid --scale SCALE` argument to manually change the unit.

**Comment by zerothi** [comment]
@anshugaur did my comment help? I'll assume it has been fixed in a couple of days.

Thanks for opening the issue.

**Comment by anshugaur** [comment]
Thanks, @zerothi. The issue is partially resolved. Preserving the name helps in converting the energy units from Siesta (Ry) to sisl (eV) using 'sgrid'. However, the dimensions still remain in 'bohr', which is not really a problem as these can be changed while plotting.

**Comment by zerothi** [comment]
Hi, yeah the units of the lattice vectors are primarily determined by the default units of the output file. I.e. the cube file defaults to writing in Bohr. While xsf *must* be in Ang. So I would say this is unconventional to change. As you say it is quite easy to do when plotting.

**Comment by zerothi** [comment]
I'll then consider this resolved, thanks!
