### ISSUE TITLE
Plotly figures not rendering in online docs

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#958]
Plotly figures in the online docs don't currently render and show errors like:

```
 Data type cannot be displayed: application/vnd.plotly.v1+json
```
Additionally, lots of `nodify` INFO lines are visible.

See for instance [GeometryPlot.html](https://zerothi.github.io/sisl/visualization/showcase/GeometryPlot.html) and screenshot below.

As far as I've been able to investigate this, a possible solution could be to insert the following in the docs notebooks:
```python
# rendering fix
import plotly.io as pio
pio.renderers.default = "iframe"

# suppress nodify INFO
import logging
logging.disable(logging.INFO)
```

<img width="750" height="1111" alt="Image" src="https://github.com/user-attachments/assets/430d25f9-531d-4d3a-ba16-32aaed410ca3" />

**Comment by zerothi** [comment]
This should work now, I have changed it to `notebook_connected` to reduce size, it however, has the side-effect of downloading the plotly thing from the web... And more than once... :(

So the real choice is if we want an interactive plot, or just the png, the former is bandwidth heavy (good internet connection), the latter is simpler, faster, but non-interactive.

**Comment by tfrederiksen** [comment]
It still doesn't work on my side:

<img width="1741" height="945" alt="Image" src="https://github.com/user-attachments/assets/6323c813-a52f-43a6-901b-8be705091ac9" />

Also, as a side remark, most thumbnails seem to be missing here: https://zerothi.github.io/sisl/visualization/index.html

**Comment by zerothi** [comment]
Could you try and close your browser, or open an incognito, just to ensure it's not a cache thing.. There were a couple of failed iterations. The file-not-found was one of the trials.

As for the log-info, that will be fixed in a coming commit. Oddly enough I don't see it locally... ;(
